//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachBorisov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiletyBDEntities : DbContext
    {
        private static BiletyBDEntities _context;
        public BiletyBDEntities()
            : base("name=BiletyBDEntities")
        {
        }

        public static BiletyBDEntities GetContext()
        {
            if (_context == null)
                _context = new BiletyBDEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colleges> Colleges { get; set; }
        public virtual DbSet<Comisions> Comisions { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Specialities> Specialities { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
