//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachBorisov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int ID { get; set; }
        public int Speciality_ID { get; set; }
        public int Teacher_ID { get; set; }
        public int Comision_ID { get; set; }
        public int Colledge_ID { get; set; }
        public Nullable<int> Semestr { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Colleges Colleges { get; set; }
        public virtual Specialities Specialities { get; set; }
        public virtual Teachers Teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
